### ISSUE TITLE
Support for the include directive

### ISSUE THREAD

**Issue by PierreR** [abo-abo/helm-make#14]
I have a make file that contains a single include directive that points to another Makefile:

```
include bin/Makefile
```
Unfortunately this is not supported by `helm-make`. I cannot use `helm-make-build-dir` because `make` needs to be run at the root of the project.

Would it be possible to support such setting ?

**Comment by cslux** [comment]
Hmm, did you try setting `helm-make-list-target-method` to `qp`?
``` emacs-lisp
(setq helm-make-list-target-method 'qp)
```

**Comment by PierreR** [comment]
Well no ... I didn't know that option. Thanks ! It works flawlessly.

**Comment by abo-abo** [comment]
Thanks, @cslux :+1:

**Comment by cslux** [comment]
My pleasure!
