### ISSUE TITLE
Certian types of targets are impossible to choose

### ISSUE THREAD

**Issue by mskorzhinskiy** [abo-abo/helm-make#19]
Some types of targets are impossible to choose: something like "rpm-%".

Example of such target
rpm-%:
	$(MAKE) -C rpm/ $(@:rpm-%=%)

May be it's a good idea to allow users of helm-make to write their own make target without checking of its existence in a Makefile.

**Comment by abo-abo** [comment]
> rpm-%:

I don't like this approach, it seems error-prone. Wouldn't it be better to just `setenv` rvm and use:

    rvm =? rvm
    
    ...
    
    $(rvm)
