### ISSUE TITLE
'qp' target method could be dangerous! Please take note.

### ISSUE THREAD

**Issue by ackalker** [abo-abo/helm-make#22]
Using the 'qp' target method could be dangerous, as it might execute arbitrary shell or system commands in some cases. I think it is worthwile to note this in the documentation.

Take this Makefile snippet (I say it is harmless, but don't take my word for it :smile:):

```makefile
RR := $(shell xdg-open "https://www.youtube.com/watch?v=dQw4w9WgXcQ")

all:
	@echo "$(RR) Fooled ya! :)"
```

Depending on system setup, some (un)expected things could happen when selecting a make target. You have been warned :smile:)

**Comment by ackalker** [comment]
ha, `.DEFAULT` seems to prevent this. I've reported a similar issue in `flycheck` which caused the maintainer to drop support for Makefile checking entirely.
I might just reopen that, then...

**Comment by ackalker** [comment]
Reopening, the problem still exists with simply expanded variables (assigned to using `:=`), see updated first comment.

**Comment by abo-abo** [comment]
Well `-qp` isn't the default setting. And even if it is, it's user's own makefile. And even if it isn't, the issue still belongs with `GNU make`, instead of `helm-make`.

I'm eager to close this issue, unless @cslux has any comment on a potential fix.

**Comment by cslux** [comment]
> Well, -qp isn't the default setting. And even if it is, it's user's own makefile. And even if it isn't, the issue still belongs with GNU make, instead of helm-make.

I don't have much to add. I understand your concern @ackalker, but I agree it is a GNU make issue. Fact is, we would need to report this than to the bash-completion maintainer as well, since they use basically the same approach to offer target completion for Makefiles [bash-completion](https://github.com/scop/bash-completion/blob/master/completions/make).

**Comment by ackalker** [comment]
@abo-abo @cslux Thank you both for your quick replies.
I understand that this is a GNU Make issue, and I'm not asking for any changes to `helm-make`, just that users be made aware of the potential risks with using the `qp` setting.

**Comment by abo-abo** [comment]
@ackalker Thanks, noted. But it's also true that running any of the makefile targets would also run the extra side-effect code. So the user was kind of planning to run the side-effect code anyway, unless he only wanted to see the list of targets and <kbd>C-g</kbd> to cancel.
