### ISSUE TITLE
PR  #24 breaks  building project with makefile in `helm-make-buildir' or  "build" 

### ISSUE THREAD

**Issue by cslux** [abo-abo/helm-make#24]
Solution:
   Append "build" or value of \`helm-make-buildir' to the **-C** option of `make`.

regards,
Christian

**Comment by abo-abo** [comment]
I don't understand what you mean. You have a fix?

**Comment by cslux** [comment]
What I mean is: In `helm--make` the variable `default-directory` will be set to the path where the makefile is located. This can be the project root directory or projcet root + build or project root + `helm-make-build-dir`, so make gets called in that directory, but after #24 `make` always switches to `projectile-project-root`. The argument to the make `-C` option should be the same as the variable `default-directory` in `helm--make` will be set.

I'll create a PR.

**Comment by cslux** [comment]
@lszekeres Why not call `recompile`?
