### ISSUE TITLE
helm-multi-match does not work

### ISSUE THREAD

**Issue by dvzubarev** [abo-abo/helm-make#26]
Steps to reproduce:
1. Paste this into Makefile,
`test_target:1.c
	clang-3.9 ./1.c -o out`
2. M-x helm-make
3. type 'te tar'
4. no candidates

I expect that test_target candidate will be available.

**Comment by dvzubarev** [comment]
Sorry, I forgot to mention that I use emacs 25.1.2 on Ubuntu 16.04.

**Comment by cslux** [comment]
@dvzubarev I see! I currently don't know why it does not work. According to the helm README it should work.

> Helm support by default multi pattern matching, it is the standard way of matching in helm. E.g You can use a pattern like "foo bar" to match a line containing "foo" and "bar" or "bar" and "foo". Each pattern can be a regexp.

I will look into that soon (today or tomorrow)

Thanks for the report!

**Comment by dvzubarev** [comment]
Thank you, the problem is fixed!
