### ISSUE TITLE
Interest check: Ninja support?

### ISSUE THREAD

**Issue by randomphrase** [abo-abo/helm-make#28]
Hi, I was just wondering if you had considered supporting the [Ninja](https://ninja-build.org/) build tool? I think there's enough similarities between Ninja and Make that it might make sense - but I understand if you think otherwise.

From a brief look I think the following changes could be made to support Ninja:

- Add a new function to generate a list of targets from a Ninja build file. Fortunately Ninja supports a `-t targets` option which will output the targets in an easily parseable form.
- Minor tweaks to the command line generation (mainly avoid using `-j` I think)
- Not much else, probably

I'm happy to submit a PR but just wanted to check your interest before starting work. Thanks.

**Comment by cslux** [comment]
@randomphrase This is good ieade in my opinion.
 
> Minor tweaks to the command line generation (mainly avoid using -j I think)

Ninja supports job count as well, in fact the format `%s -C %s -j%d %%s"` should work with ninja too.

**Comment by randomphrase** [comment]
@cslux I should have clarified this comment. I just mean that Ninja has different behavior to Make in this regard; if the `-j` argument is omitted, it defaults to the CPU count instead of 1. This generally means that (at least for me!) omitting the `-j` argument is usually better than specifying it.

**Comment by cslux** [comment]
@randomphrase Ok, now I got it! Maybe we should add something to retrieve the available number of CPU cores, and use that number +1 by default instead of 1.

**Comment by cslux** [comment]
Some useful links about getting the CPU count on various systems.

http://nullprogram.com/blog/2015/10/14/

http://stackoverflow.com/questions/20666556/getting-number-of-processors-in-emacs

**Comment by abo-abo** [comment]
I'm all for Ninja support. PRs welcome.

**Comment by cslux** [comment]
@randomphrase Will you implement it? If not, I'll like to do it.
