### ISSUE TITLE
TRAMP prefix breaks compilation

### ISSUE THREAD

**Issue by tommy-u** [abo-abo/helm-make#33]
Hi,
I'm trying to use `SPC c c` to compile on a remote machine using tramp mode. The problem I'm seeing is the tramp prefix `/ssh:<user>@<host>:` is being passed in along with the makefile directory path on the make line:
```
make -C /ssh:<user>@<host>:<make dir path> -j1 all
```
Which fails of course. Am I simply using the tool incorrectly, or could this use a fix?

To recreate:
1) With a fresh .spacemacs, accept the defaults when prompted.
2) Add c-c++ layer.
3) Add the following lines to your user-config:
```
  (setq enable-remote-dir-locals t)
  (put 'helm-make-build-dir 'safe-local-variable 'stringp)
```
4) Have a project on a remote machine with a .projectile file
5) Have a .dir-locals.el file in the project root with the following:
```
((c++-mode (helm-make-build-dir . <path to makefile>)))
```
6) Open a .cc file in the project and attempt `SPC c c`, run a target and see:
```
make: *** /ssh:<user>@<host>:<path to makefile>: No such file or directory.  Stop.
```

Fixing:
It looks like this is the line responsible for building the make command: https://github.com/abo-abo/helm-make/blob/master/helm-make.el#L344 .

**Comment by abo-abo** [comment]
Works fine for me, when compiling on localhost through tramp. I don't have any extra config: I just open a file or directory on remote and call `helm-make`.

Might be a spacemacs specific issue. If you know how to fix it, PRs welcome.

**Comment by tommy-u** [comment]
Thanks for responding. 
I shouldn't have jumped right into the spacemacs setup. I agree helm-make works great when you're in the same directory as your makefile. When you're editing source in a subdirectory, however, you get a no makefile error because helm-make uses your current directory. I can replicate the above error in vanilla emacs with the following.

1) I dropped this in my .emacs.d/init.el
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(put 'helm-make-build-dir 'safe-local-variable 'stringp)
(setq enable-remote-dir-locals t)
```
2) Add helm-make package.
3) Enter a remote project as above (has a .projectile, has a .dir-locals.el).
4) Running helm-make-projectile brings the:
```
make: *** /ssh:<user>@<host>:<path to makefile>: No such file or directory.  Stop.
```
error.

I think simply trimming the tramp injected scp / ssh line would fix this. If there's nothing obvious I'm missing, I'd be happy to attempt a PR.
