### ISSUE TITLE
When detecting ninja "build" directory should override helm-make-command to "ninja" automatically

### ISSUE THREAD

**Issue by alexmurray** [abo-abo/helm-make#35]
I use projects with both standard make and with ninja (via meson) - I would rather not have to customise `helm-make-command` with dir-locals or similar for the ninja specific projects - instead this should be detected automatically due to the presence of `${projectile-project-root}/build/ninja.build"` and `helm-make-command` should automatically be `ninja` in this case

**Comment by abo-abo** [comment]
I'll need some help with this, since I never used `ninja`. PRs welcome.

**Comment by cslux** [comment]
When we detect the build system automatically, the choice `ninja` in the `helm-make-list-target-method` defcustom would be obsolete, right.

I'll cook something up.

PR coming soon.

**Comment by alexmurray** [comment]
Awesome - thanks works great!

**Comment by cslux** [comment]
Nice to hear.
