### ISSUE TITLE
`helm-make-named-buffer` with Projectile project root

### ISSUE THREAD

**Issue by peterbecich** [abo-abo/helm-make#40]
`helm-make-named-buffer` presently keeps compilations of different Make targets in separate buffers.  However, assuming I'm using it correctly, concurrent compilation of separate projects with the same target names will cause the latter `Make` to stop the former `Make` and take over its `*compilation (TARGET)*` buffer.

Can this be avoided if `helm-make-named-buffer` includes `projectile-project-root` in the name of the compilation buffer?

Thanks for your time -- this tool is super useful to me.

**Comment by cslux** [comment]
Including `projectile-project-root` works only for `helm-make-projectile` but not for `helm-make`, but  using the value of `default-directory` would be an option.

`*compilation in DEFAULT-DIRECTORY (TARGET)*`

**Comment by peterbecich** [comment]
Thank you @cslux !
