### ISSUE TITLE
Question/Feature: Add function to retrieve available number of cores

### ISSUE THREAD

**Issue by cslux** [abo-abo/helm-make#46]
Hey @abo-abo!

Does it makes sense to add code to helm-make to retrieve the available number of CPU cores. 
Example implementation: https://nullprogram.com/blog/2015/10/14/

I actually think this feature should be part of emacs/compile.el. 

Possible implementation.
- Create a function which returns the CPU cores.
- Create a helm-make defcustom, e.g. `helm-make-njobs`, which is either a number (default 1) or a function returning a number.
- A universal prefix would overrule `helm-make-njobs` and is used instead.  

regards,
Christian

**Comment by abo-abo** [comment]
Sounds good. Please PR.
