### ISSUE TITLE
Possibility to set default target and command

### ISSUE THREAD

**Issue by joakim-hove** [abo-abo/helm-make#48]
I use spacemacs with helm and projectile as my C++ development environment. My typical workflow is a quite tight loop like this:

1. Edit code
2. Recompile target: `currently_failing_test`
3. if (compiles)
         run `currently_failing_test`
4. Go back to 1

For me it would be very valuable if I could run `helm-make-projectile` without selecting the target - it will be the same for quite some time; i.e. I could set a variable `helm-make-default-target` - and if that was set the target selection was bypassed. Would something like that be possible? I could have a go at implementing it myself - if there is a chance it would be merged?

Also I would like the number of cores to be set - without having to pass the numeric argument each time; my workstation has the same number of cores after all :-)

**Comment by cslux** [comment]
Hey @joakim-hove!

> I could set a variable `helm-make-default-target` - and if that was set the target selection was bypassed. Would something like that be possible? I could have a go at implementing it myself - if there is a chance it would be merged?

That should be straightforward, and makes sense to me. Actually, the used target should be  selected the next time you call `helm-make-projectile`, but that is somewhat broken at the moment. Though, you would still need to hit enter.

 > Also I would like the number of cores to be set - without having to pass the numeric argument each time; my workstation has the same number of cores after all :-)

I actually created a PR for that, see  #47. Please test. You would need to set `helm-make-nproc` to your preferred value, or 0 to automatically determine the available number of CPU cores.

**Comment by joakim-hove** [comment]
> I actually created a PR for that, see #47. Please test. You would need to set helm-make-nproc to your preferred value, or 0 to automatically determine the available number of CPU cores.

Cool - I'll give that a spin.

**Comment by abo-abo** [comment]
Is the problem still there? I have the default target pre-selected both for `helm-make` and `helm-make-projectile`.

**Comment by cslux** [comment]
@abo-abo For me, yes!

**Comment by cslux** [comment]
I personally would also expect that the last executed target will be preselected which might be different from what I have entered.

**Comment by cslux** [comment]
With that Makefile it sometime happens that the target `install` gets selected even though I have entered `all`, which also got selected by helm. i.e. I did not moved point.
``` Makefile
all:
install:
build-all:
```

**Comment by abo-abo** [comment]
What's your config?

**Comment by cslux** [comment]
``` emacs-lisp
(use-package helm-make
    :load-path "~/Developing/third_party/helm-make"
    :bind (("<f5>"   . helm-make)
           ("C-<f5>" . helm-make-projectile))
    :config
    (setq helm-make-list-target-method 'qp
          helm-make-fuzzy-matching t
          helm-make-cache-targets t
          helm-make-nproc 0
          helm-make-sort-targets t))
```
Without `helm-make-fuzzy-matching` it's ok. But after you have hit enter when it got re-selected, the `helm-make-target-history` will contain some new value at `car`.

**Comment by abo-abo** [comment]
Thanks, please test.
