### ISSUE TITLE
build targets not shown

### ISSUE THREAD

**Issue by QuantumAnon** [abo-abo/helm-make#52]
When I call `helm-make` the helm buffer appears, but no build targets are shown.
I've tried reinstalling both helm and helm-make but neither seems to fix the issue.
This is the case when I'm calling `helm-make` from a directory with a makefile in it and when I call `helm-make-projectile`.

Edit: Running helm-make-20190630.1606 on emacs 26.2.

**Comment by abo-abo** [comment]
Works fine for me. My config:

```elisp
(use-package helm-make
  :commands (helm-make helm-make-projectile)
  :config (setq helm-make-completion-method 'ivy))
```

**Comment by QuantumAnon** [comment]
Used `setq helm-make-completion-method 'ido` instead and I can compile documents now.
Any idea why helm wasn't working, or how I could diagnose it?

**Comment by abo-abo** [comment]
No idea. There hasn't been any change to `helm-make` in 3 weeks. And no other users, myself included, seem to have your problem.

Try reinstalling your packages and restarting Emacs.

**Comment by QuantumAnon** [comment]
Still doesn't work after reinstalling emacs and packages.
I'll stick with ido for now then, it's probably an issue with something else.
Closing the issue since it doesn't appear to be a widespread problem.

**Comment by QuantumAnon** [comment]
Reopening this because I've diagnosed the issue.
helm-make seems to ignore targets which are followed by a space.
For example, with this makefile you'd expect to see two targets, foo.copy and bar.copy.

```
SHELL := /bin/sh

foo.copy : foo
	cp foo foo.out

bar.copy: bar
	cp bar bar.out
```

Yet I only see one, bar.copy.

Is anyone else able to reproduce this?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by QuantumAnon** [comment]
Works, thanks.
